{
    'name': 'BAK (Berita Acara Kejadian)',
    'version': '1.0',
    'summary': 'BAK Module',
    'category': 'Fleet Custom',
    'author': 'Kurnia Galuh',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'fleet',
        'mail',
        'account',
        'stock',
        'purchase',
        'x_service_planning',
        'x_spk',
        'x_spk_invoice',
    ],
    'data': [
        'security/bak_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        "report/bak_report.xml",
        'views/bak_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/product_template_views.xml',
    ],
    'installable': True,
    'application': True,
}