from odoo import fields, models


class AccountMove(models.Model):
    _inherit = "account.move"

    x_is_refinancing_adjustment = fields.Boolean(
        string="Refinancing Depreciation Adjustment",
        copy=False,
        help="Set on the prorata depreciation entry generated by a refinancing "
        "(leaseback / sell / dispose) closing. Such an entry is part of the "
        "refinancing transaction, not a normal depreciation of the asset.",
    )
    x_refinancing_type = fields.Selection(
        [
            ("leaseback", "Leaseback"),
            ("sell", "Sell"),
            ("dispose", "Dispose"),
        ],
        string="Refinancing Type",
        copy=False,
        help="Kind of refinancing this disposal entry represents.",
    )
