# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import UserError


class AccountMove(models.Model):
    _inherit = 'account.move'

    # Compatibility for databases restored from a newer Odoo 19 revision.
    # The newer account.move form references this field, while older local
    # Odoo 19 sources only provide is_draft_duplicated_ref_ids.
    is_exact_move_duplicate = fields.Boolean(
        compute='_compute_is_draft_duplicated_ref_ids',
    )

    active = fields.Boolean(default=True, tracking=True)

    x_is_rental_invoice = fields.Boolean(
        string='Is Rental Invoice',
        default=False,
        help='Flag to identify invoices auto-generated by the Rental Invoicing system.'
    )

    x_rental_period_start = fields.Date(
        string='Rental Period Start',
        help='Start date of the rental period covered by this invoice.'
    )

    x_rental_period_end = fields.Date(
        string='Rental Period End',
        help='End date of the rental period covered by this invoice.'
    )

    x_rental_delivery_date = fields.Date(
        string='Rental Delivery Date',
        help='Actual delivery date group for non-consolidated invoices.'
    )

    @api.depends('duplicated_ref_ids')
    def _compute_is_draft_duplicated_ref_ids(self):
        super()._compute_is_draft_duplicated_ref_ids()
        for move in self:
            move.is_exact_move_duplicate = any(
                move.ref
                and move.ref == duplicate.ref
                and move.move_type == duplicate.move_type
                and move.partner_id == duplicate.partner_id
                and move.invoice_date == duplicate.invoice_date
                and move.amount_total == duplicate.amount_total
                and move.is_purchase_document()
                for duplicate in move.duplicated_ref_ids
            )

    def _update_related_rental_tracking(self):
        for move in self:
            if move.x_is_rental_invoice or move.invoice_origin:
                sale_lines = move.line_ids.sale_line_ids
                if sale_lines:
                    sale_lines._update_invoice_tracking()

    def _post(self, soft=True):
        res = super(AccountMove, self)._post(soft=soft)
        self._update_related_rental_tracking()
        return res

    def button_draft(self):
        res = super(AccountMove, self).button_draft()
        self._update_related_rental_tracking()
        return res

    def button_cancel(self):
        res = super(AccountMove, self).button_cancel()
        self._update_related_rental_tracking()
        return res

    def unlink(self):
        for record in self:
            if record.state not in ('draft', 'cancel'):
                raise UserError(_("You can only delete invoices in Draft or Cancelled status. For posted invoices, please archive them instead."))
        sale_lines = self.line_ids.sale_line_ids
        res = super(AccountMove, self).unlink()
        if sale_lines:
            sale_lines._update_invoice_tracking()
        return res


class AccountMoveLine(models.Model):
    _inherit = 'account.move.line'

    x_plate_number = fields.Char(
        string='Plate Number/Asset Number',
        help='Vehicle plate number or asset number associated with this invoice line.'
    )

    x_billing_month = fields.Char(
        string='Billing Month',
        help='Billing month indicator (e.g., "1 of 12").'
    )
