from . import spk_stock_forecast_mixin
from . import product_template
from . import fleet_vehicle
from . import stock_move
from . import spk_master_data
from . import spk_approval_matrix
from . import spk_approval_tracking
from . import spk_approval_line
from . import spk_product_line
from . import fleet_spk
from . import purchase_order
from . import spk_tyre_line
from . import spk_aki_line
from . import spk_approval_action_wizard
from . import spk_tyre_aki_wizard
