from . import product_template
from . import fleet_vehicle
from . import spk_master_data
from . import res_groups_approval_role
from . import fleet_spk
from . import spk_sparepart_line
from . import spk_service_line
from . import spk_tyre_line
from . import spk_aki_line
from . import spk_on_risk_product
from . import spk_approval_line
from . import spk_approval_matrix
from . import spk_approval_action_wizard
from . import spk_tyre_aki_wizard
